version: 2

models:
  - name: stg_departments
    columns:
      - name: id_department
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
          - accepted_values:
              values: [ 'Electronics', 'Furniture' ]
      - name: id_head
        tests:
          - not_null
          - relationships:
              to: ref('stg_people')
              field: id_person

  - name: stg_order_items
    columns:
      - name: id_order_item
        tests:
          - unique
          - not_null
      - name: id_order
        tests:
          - not_null
      - name: id_product
        tests:
          - not_null
          - relationships:
                to: ref('stg_products')
                field: id_product
      - name: id_customer
        tests:
          - not_null
          - relationships:
              to: ref('stg_people')
              field: id_person
      - name: id_manager
        tests:
          - not_null
          - relationships:
                to: ref('stg_people')
                field: id_person
      - name: price
        tests:
          - not_null
      - name: purchase_date
        tests:
          - not_null
      - name: payment_method
        tests:
          - not_null
          - accepted_values:
              values: [ 'Credit Card', 'PayPal', 'Cash', 'Bank Transfer' ]
      - name: shipping_method
        tests:
          - not_null
          - accepted_values:
              values: [ 'Express', 'Standard', 'Pickup' ]
      - name: quantity
        tests:
          - is_non_negative

  - name: stg_people
    columns:
      - name: id_person
        tests:
          - unique
          - not_null
      - name: role
        tests:
          - not_null
      - name: name
        tests:
          - not_null
      - name: phone_num
        tests:
          - not_null
      - name: id_manager
        tests:
          - not_null
      - name: start_date
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: id_product
        tests:
          - unique
          - not_null
      - name: id_warehouse
        tests:
          - not_null
      - name: warehouse_city
        tests:
          - not_null
      - name: warehouse_address
        tests:
          - not_null
      - name: responsible_warehouse
        tests:
          - not_null
          - relationships:
              to: ref('stg_people')
              field: id_person
      - name: name
        tests:
          - not_null
      - name: category
        tests:
          - not_null
          - accepted_values:
              values: [ 'Electronics', 'Furniture', 'Office Supplies', 'Appliances' ]
      - name: price
        tests:
          - not_null
          - is_positive
      - name: description
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null

  - name: stg_status_logs
    columns:
      - name: id_order_item
        tests:
          - not_null
          - relationships:
              to: ref('stg_order_items')
              field: id_order_item
      - name: id_status
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: [ 'Pending', 'Shipped', 'Delivered', 'Cancelled', 'Returned' ]
      - name: status_timestamp
        tests:
          - not_null